version: "3.8"

services:
  web:
    image: nginx:latest
    # build: ./local/docker
    container_name: web
    ports:
      - 8080:80
    stdin_open: true
    tty: true
    privileged: true
    # networks:
    #   app_net:
    #     ipv4_address: 172.18.0.2
    # volumes:
      # - ${WEB_DIR}:${DOCKER_WEB_DIR}
      # - ${WEB_DIR}:/var/www/html
      #- ${NGINX_CONF_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf
    # working_dir: ${DOCKER_WEB_DIR}
    # environment:
    #   - NGINX_HOST=0.0.0.0
    #   - NGINX_PORT=80
      # - ${USER_NAME}
      # - ${USER_ID}
      # - ${GROUP_NAME}
      # - ${GROUP_ID}
    # depends_on:
      # - db
    # restart: always

  # db:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ${DB_DIR}/conf:/etc/mysql/conf.d
  #     - ${DB_DATA_DIR}:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD
  #     - MYSQL_DATABASE
  #     - MYSQL_USER
  #     - MYSQL_PASSWORD
  #     - UID
  #     - UNAME
  #     - GID
  #     - GNAME
  #   restart: always
  #   container_name: db
  #   user: $UID:$GID
  #   tty: true

